user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

ticket_manager:
    resource: "@TicketManagerBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
